Repository 4paradigm/openmldb-docs-zh, pull requests merged in 2022-02, with the labels that each got.

#40 feat: fix last join image
  reference/sql/dql/images/last_join_with_order2.png
Labels: documentation

#45 fix: fix the keys of openmldb batch config
  tutorial/openmldbspark_distribution.md
Labels: bug, documentation

#44 feat: add variable show and set statement and other docs bug fix
  README.md
  SUMMARY.md
  reference/sql/ddl/SET_STATEMENT.md
  reference/sql/ddl/SHOW_VARIABLES_STATEMENT.md
  reference/sql/ddl/reference.md
  reference/sql/deployment_manage/ONLINE_SERVING_REQUIREMENTS.md
  reference/sql/dql/WINDOW_CLAUSE.md
  tutorial/standalone_vs_cluster.md
Labels: documentation

#48 feat: update python_sdk.md : for currently don't support "drop database" in python SDK
  quickstart/python_sdk.md
Labels: enhancement
