Repository 4paradigm/openmldb-docs-zh, pull requests merged in 2022-01, with the labels that each got.

#15 fix: image url fix
  quickstart/openmldb_quickstart.md
Labels: bug, documentation

#18 feat: add taskmanger docs
  SUMMARY.md
  deploy/install_deploy.md
  reference/sql/task_manage/SHOW_JOB.md
  reference/sql/task_manage/SHOW_JOBS.md
  reference/sql/task_manage/STOP_JOB.md
  reference/sql/task_manage/SUBMIT_JOB.md
  reference/sql/task_manage/reference.md
Labels: documentation

#20 feat: fix readme
  README.md
  SUMMARY.md
  quickstart/openmldb_quickstart.md
  tutorial/content.md
  tutorial/data_import.md
  tutorial/openmldbspark_distribution.md
  use_case/case1.md
  use_case/taxi_tour_duration_prediction.md
Labels: documentation

#36 fix: update function link
  reference/sql/functions_and_operators/Files/udfs_8h.md
  tutorial/data_import.md
Labels: bug
